language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # Use this little line of shell script to generate list of files to compile
    # for x in $(find examples -maxdepth 2 -mindepth 2); do echo "    - PLATFORMIO_CI_SRC="$x ; done
    # --- Portuguese - Portugol Version ---
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex02.Pisca
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex08.Desvanecer
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex04.DigitalLeituraSerial
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex01.CodigoMinimo
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex05.LeituraAnalogicaSerial
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex07.RedirecionaSerial
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex09.Melodia
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex06.LeituraAnalogicaVoltagem
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex03.Botao
    - PLATFORMIO_CI_SRC=examples/PT-Portugol/Ex10.Esmanecer

install:
    - pip install -U platformio
    # Install libraries needed
    # -- no libraries need 
    # Update libraries to prevent cache of old versions
    # -- no libraries to update

script:
    - platformio ci --lib="." --board=uno --board=miniatmega328 --board=pro16MHzatmega328 --board=megaatmega2560 --board=megaatmega1280
